### ISSUE TITLE
'no more data'

### ISSUE THREAD

**Issue by brennongs** [iizukanao/node-rtsp-rtmp-server#116]
regarding [this comment](https://github.com/iizukanao/node-rtsp-rtmp-server/issues/70#issuecomment-288267798), I am having the same issue as `small.mp4`, the `no more data` issue. Did you ever figure out a fix for that one? I can stream a video converted from YouTube via VLC, but not videos of my own making. @iizukanao or @jandrieu , if you have any input, that would also be appreciated. error below:

```sh
2018-03-30 15:02:49.718 [rtsp/http/rtmpt:client=c2] connected
/Users/brennon/Codes/node-rtsp-rtmp-server/server.js:47
    throw err;
    ^

Error: read_byte error: no more data
    at Bits.read_byte (/Users/brennon/Codes/node-rtsp-rtmp-server/bits.js:255:17)
    at Bits.read_uint32 (/Users/brennon/Codes/node-rtsp-rtmp-server/bits.js:180:19)
    at MPEG4BitRateBox.read (/Users/brennon/Codes/node-rtsp-rtmp-server/mp4.js:2646:37)
    at MPEG4BitRateBox.Box (/Users/brennon/Codes/node-rtsp-rtmp-server/mp4.js:834:14)
    at new MPEG4BitRateBox (/Users/brennon/Codes/node-rtsp-rtmp-server/mp4.js:2638:52)
    at Function.Box.parse (/Users/brennon/Codes/node-rtsp-rtmp-server/mp4.js:1035:20)
    at AVCSampleEntry.read (/Users/brennon/Codes/node-rtsp-rtmp-server/mp4.js:2623:32)
    at AVCSampleEntry.Box (/Users/brennon/Codes/node-rtsp-rtmp-server/mp4.js:834:14)
    at AVCSampleEntry.VisualSampleEntry [as constructor] (/Users/brennon/Codes/node-rtsp-rtmp-server/mp4.js:1763:54)
    at new AVCSampleEntry (/Users/brennon/Codes/node-rtsp-rtmp-server/mp4.js:2613:51)
```

**Comment by avanerk** [comment]
Commenting out these lines: https://github.com/iizukanao/node-rtsp-rtmp-server/blob/master/bits.coffee#L214-L215 for some reason seems to work for me
