### ISSUE TITLE
Error: read_byte error: no more data

### ISSUE THREAD

**Issue by bewithme** [iizukanao/node-rtsp-rtmp-server#129]
after  server started, I connect it by vlc player with the mrl  rtsp://localhost:80/file/mp4:1.mp4 ,errors show as bellow and server is crash, what is wrong?

2019-03-29 17:15:45.929 attachRecordedDir: dir=file app=file
2019-03-29 17:15:45.938 [rtmp] server started on port 1935
2019-03-29 17:15:45.939 [rtsp/http/rtmpt] server started on port 80
2019-03-29 17:16:05.153 [rtsp/http/rtmpt:client=c1] connected
2019-03-29 17:16:05.163 [mp4] warning: skipping unknown (not implemented) box type: wide (0x77696465)
/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/server.coffee:46
    throw err;
    ^

Error: read_byte error: no more data
    at Bits.read_byte (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/bits.coffee:215:15)
    at Bits.read_uint32 (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/bits.coffee:155:13)
    at MPEG4BitRateBox.read (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:1983:24)
    at MPEG4BitRateBox.Box (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:682:8)
    at new MPEG4BitRateBox (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:1978:7)
    at Function.Box.parse (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:854:18)
    at AVCSampleEntry.read (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:1971:26)
    at AVCSampleEntry.Box (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:682:8)
    at AVCSampleEntry.VisualSampleEntry [as constructor] (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:1385:7)
    at new AVCSampleEntry (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:1964:7)
    at Function.Box.parse (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:835:16)
    at SampleDescriptionBox.read (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:1309:30)
    at SampleDescriptionBox.Box (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:682:8)
    at new SampleDescriptionBox (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:1276:7)
    at Function.Box.parse (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:793:16)
    at SampleTableBox.Container.read (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:864:17)
    at SampleTableBox.Box (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:682:8)
    at SampleTableBox.Container [as constructor] (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:859:7)
    at new SampleTableBox (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:875:7)
    at Function.Box.parse (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:791:16)
    at MediaInformationBox.Container.read (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:864:17)
    at MediaInformationBox.Box (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:682:8)
    at MediaInformationBox.Container [as constructor] (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:859:7)
    at new MediaInformationBox (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:884:7)
    at Function.Box.parse (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:779:16)
    at MediaBox.Container.read (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:864:17)
    at MediaBox.Box (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:682:8)
    at MediaBox.Container [as constructor] (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:859:7)
    at new MediaBox (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:887:7)
    at Function.Box.parse (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:771:16)
    at TrackBox.Container.read (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:864:17)
    at TrackBox.Box (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:682:8)
    at TrackBox.Container [as constructor] (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:859:7)
    at new TrackBox (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:893:7)
    at Function.Box.parse (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:763:16)
    at MovieBox.Container.read (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:864:17)
    at MovieBox.Box (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:682:8)
    at MovieBox.Container [as constructor] (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:859:7)
    at new MovieBox (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:872:7)
    at Function.Box.parse (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:757:16)
    at MP4File.parse (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/mp4.coffee:88:17)
    at Function.MP4Stream.create (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/avstreams.coffee:222:13)
    at Object.get (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/avstreams.coffee:368:30)
    at /Users/xxxx/Downloads/node-rtsp-rtmp-server-master/rtsp.coffee:1404:30
    at RTSPServer.authenticate (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/rtsp.coffee:1129:14)
    at /Users/xxxx/Downloads/node-rtsp-rtmp-server-master/rtsp.coffee:1389:8
    at RTSPServer.livePathConsumer (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/server.coffee:30:5)
    at RTSPServer.consumePathname (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/rtsp.coffee:1142:8)
    at RTSPServer.respondDescribe (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/rtsp.coffee:1385:6)
    at RTSPServer.respond (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/rtsp.coffee:1976:8)
    at RTSPServer.handleOnData (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/rtsp.coffee:908:6)
    at Socket.<anonymous> (/Users/xxxx/Downloads/node-rtsp-rtmp-server-master/rtsp.coffee:451:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

**Comment by mobileFX** [comment]
Same here
