### ISSUE TITLE
Not implemented: nal_unit_type=24

### ISSUE THREAD

**Issue by dejarno** [iizukanao/node-rtsp-rtmp-server#13]
Hi

95% of the time everything works perfect, great job!
Except with some videos I'm getting the following error:
```
Error: Not implemented: nal_unit_type=24
    at Object.api.readH264Payload (rtp.js:486:19)
    at Object.api.parseH264Packet (rtp.js:465:25)
    at RTPParser.feedUnorderedH264Buffer (rtp.js:64:20)
    at RTSPServer.onUploadVideoData (rtsp.js:1924:31)
    at Socket.<anonymous> (rtsp.js:497:26)
    at Socket.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:441:8)
```
I already tried to drop the frames, but that results in an other error.
If you want a video that produces the error just let me know and I will send you one.

Thanks!

**Comment by iizukanao** [comment]
Hi, thanks for reporting the bug!
I've updated the code to address the issue, but I can't test it with a video file. Can you see if it works?

**Comment by dejarno** [comment]
It works, thanks!
