### ISSUE TITLE
There is way to set packet size on rtsp push?

### ISSUE THREAD

**Issue by Classsic** [iizukanao/node-rtsp-rtmp-server#139]
Hi, is possible define max packet size for rtsp server?
I try this command:
`ffmpeg -rtsp_transport tcp -i rtsp://ipcamera -c:v copy  -an -f rtsp -rtsp_transport tcp rtsp://localhost:80/live/ip_camera?pkt_size=1100`
but get this error:
`/app/server.coffee:46
    throw err;
    ^

TypeError: Cannot read property 'videoData' of undefined
    at RTSPServer.onInterleavedRTPPacketFromClient (/app/rtsp.coffee:802:58)
    at RTSPServer.handleOnData (/app/rtsp.coffee:841:8)
    at Socket.<anonymous> (/app/rtsp.coffee:451:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:540:20)
`
Thanks in advance.

**Comment by iizukanao** [comment]
@Classsic You can effectively set the limit of a packet size by changing the maximum size of single NAL unit at `SINGLE_NAL_UNIT_MAX_SIZE = 1358` in rtsp.coffee. However, why do you need `?pkt_size=1100` in the first place? I think your command will work if you remove that part from the destination URL.
