### ISSUE TITLE
server crashed when client play stream without audio via rtsp protocal

### ISSUE THREAD

**Issue by xxxman2008** [iizukanao/node-rtsp-rtmp-server#19]
2015-05-23 19:21:19.519 [rtmp] server started on port 1935
2015-05-23 19:21:19.573 [rtsp/http] server started on port 80
2015-05-23 19:22:27.546 [rtsp/http] client c1 connected
[rtsp/http: 1 clients]
 c1: session=38186821 addr=10.253.66.198 port=58072 type=publish-udp
2015-05-23 19:22:27.710 [rtsp] client c1 started uploading stream stream1
2015-05-23 19:24:45.330 [rtsp/http] client c2 connected
/home/pi/sources/node-rtsp-rtmp-server/server.js:41
    throw err;
          ^
Error: null channels audio is not supported
    at Object.api.getChannelConfiguration (/home/pi/sources/node-rtsp-rtmp-server/aac.js:317:17)
    at Object.api.createAudioSpecificConfig (/home/pi/sources/node-rtsp-rtmp-server/aac.js:575:36)
    at /home/pi/sources/node-rtsp-rtmp-server/rtsp.js:1444:60
    at RTSPServer.livePathConsumer (/home/pi/sources/node-rtsp-rtmp-server/server.js:24:14)
    at RTSPServer.consumePathname (/home/pi/sources/node-rtsp-rtmp-server/rtsp.js:1264:21)
    at RTSPServer.respondDescribe (/home/pi/sources/node-rtsp-rtmp-server/rtsp.js:1408:19)
    at RTSPServer.respond (/home/pi/sources/node-rtsp-rtmp-server/rtsp.js:1916:21)
    at RTSPServer.handleOnData (/home/pi/sources/node-rtsp-rtmp-server/rtsp.js:1019:19)
    at Socket.<anonymous> (/home/pi/sources/node-rtsp-rtmp-server/rtsp.js:496:28)
    at Socket.emit (events.js:107:17)

**Comment by xxxman2008** [comment]
This is  a great  project .  Difficult to express with words.

and ...is there any possible write it  use JS ?

**Comment by iizukanao** [comment]
Thanks for reporting a bug! I've just fixed that bug.

You can modify any behavior of the server using JavaScript. Please let me know if you have any difficulties.

**Comment by xxxman2008** [comment]
Thanks Iizukanao .

I've no difficult using Node.Js  .but i  not  familian with  coffee script ..:-) .

**Comment by iizukanao** [comment]
You can write your own code in JavaScript. Just load your JS script from CoffeeScript with `require`. They are interoperable.

BTW, you will be able to comfortably write CoffeeScript in a couple of hours if you already know JavaScript.
