### ISSUE TITLE
publish rtmp stream from Flash or Flash Media Encoder

### ISSUE THREAD

**Issue by mandevx** [iizukanao/node-rtsp-rtmp-server#2]
I tried to use the server by publishing the stream from flash swf and also from Flash Media Encoder . In both I got an error and server crashed .

new RTMPSession
Waiting for complete C0+C1
client type: 3
Waiting for complete C2+RTMPMessage
[rtmp] handshake success, buf.length=1936

/root/node-rtsp-rtmp-server/server.coffee:741
    throw err;
          ^
Error: Unknown AMF0 data type: 49
  at parseAMF0Data (/root/node-rtsp-rtmp-server/rtmp.coffee:292:15)
  at parseAMF0CommandMessage (/root/node-rtsp-rtmp-server/rtmp.coffee:247:14)
  at RTMPSession.handleData (/root/node-rtsp-rtmp-server/rtmp.coffee:1369:28)
  at Socket.<anonymous> (/root/node-rtsp-rtmp-server/rtmp.coffee:1446:23)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)

**Comment by iizukanao** [comment]
Closing this issue since it's too old. Please open a new issue if you still have any problems.
