### ISSUE TITLE
Server shutting down with "server.coffee: 40   throws err: TypeError: Object blalbabla"

### ISSUE THREAD

**Issue by sensorua** [iizukanao/node-rtsp-rtmp-server#25]
Hi!
I'm testing this server with 2 types of rtmp streamers - Flash Media Encoder and Teradek VidiU mini (hardware streamer for hdmi cameras)
It's all ok with first one, but i tried to connect VidiU mini, that supports RTMP streaming with h.264, and server fail's with unhandled exception (debug log listed below)
Any ideas? Please help 

2015-07-08 12:16:16.964 [rtmp:BElYtzPD] connected
[rtmp: 1 sessions]
 BElYtzPD: addr=91.202.72.98 port=39328
2015-07-08 12:16:16.968 [rtmp:handshake] warning: unknown message format, assuming format 1
2015-07-08 12:16:31.559 [rtmp:zXrA8Myz] connected
[rtmp: 2 sessions]
 BElYtzPD: addr=91.202.72.98 port=39328
 zXrA8Myz: addr=176.115.97.245 port=51143
2015-07-08 12:16:31.617 [rtmp:handshake] warning: unknown message format, assuming format 1
2015-07-08 12:16:32.849 [rtmp] publish: stream=zzz publishingType=live
2015-07-08 12:16:32.951 receive video: num_nal_units=2 pts=165473106840
2015-07-08 12:16:32.954 video: pts=165473106840 pts_diff=165473106840 md5=2b2606d nal_unit_type=7 bytes=44
2015-07-08 12:16:32.954 video: pts=165473106840 pts_diff=0 md5=ac995ac nal_unit_type=8 bytes=4
2015-07-08 12:16:32.957 receive audio: num_access_units=1 pts=165473112600
2015-07-08 12:16:32.957 audio: pts=165473112600 md5=b504dda bytes=92
2015-07-08 12:16:33.177 receive video: num_nal_units=4 pts=165473106840

/home/ubuntu/node-rtsp-rtmp-server/server.coffee:40
    throw err;
          ^
TypeError: Object gBï¿½^_ï¿½(.7ï¿½ï¿½"

**Comment by rexfm** [comment]
Interesting, I get a similar but different error coming from the same line:

pi@z108c ~/node-rtsp-rtmp-server $ ./start_server.sh
2015-09-08 08:16:22.012 [rtmp] server started on port 1935
2015-09-08 08:16:22.282 [rtsp/http] server started on port 80
2015-09-08 08:16:29.923 [custom_receiver] new connection to VideoData
2015-09-08 08:16:30.045 [custom_receiver] new connection to VideoControl
2015-09-08 08:16:30.105 [custom_receiver] new connection to AudioData
2015-09-08 08:16:30.123 [custom_receiver] new connection to AudioControl
2015-09-08 08:16:37.885 [rtsp/http] client c1 connected
2015-09-08 08:16:38.329 [rtsp/http] client c2 connected
2015-09-08 08:16:38.354 [rtsp/http] client c1 is closed
[rtsp/http: 1 clients]
 c2: session=29187955 addr=192.168.1.99 port=57389
2015-09-08 08:16:38.413 [rtsp/http] client c2 is closed
[rtsp/http: 0 clients]
2015-09-08 08:16:38.990 [rtsp/http] client c3 connected
/home/pi/node-rtsp-rtmp-server/server.coffee:40
    throw err;
          ^
TypeError: Cannot read property 'slice' of null
  at RTSPServer.livePathConsumer (/home/pi/node-rtsp-rtmp-server/server.coffee:12:38)
  at RTSPServer.consumePathname (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:1097:8)
  at RTSPServer.respondDescribe (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:1238:6)
  at RTSPServer.respond (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:1772:8)
  at RTSPServer.handleOnData (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:882:6)
  at Socket.<anonymous> (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:443:12)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:538:20)

**Comment by danielfree** [comment]
hi @sensorua  we met the same issue at server.coffee:40, turns out the issue is with "compare" method missing for some object. The solution is upgrading nodejs to > 0.12 version, see (http://stackoverflow.com/questions/29910825/why-am-i-getting-this-error-r1-buf1-comparebuf2-typeerror-object-rahul-h). 

Still @rexfm 's issue looks like a different one.

**Comment by iizukanao** [comment]
Sorry for the late reply. I have recently fixed a bunch of bugs. Could you try again with the latest code?
