### ISSUE TITLE
coffee server.coffee failed?

### ISSUE THREAD

**Issue by QQsilhonette** [iizukanao/node-rtsp-rtmp-server#33]
What "Edit config.coffee" is for?
And I have done follow your steps, but it still failed, the error is as follow: 

D:\node-rtsp-rtmp-server-master>coffee server.coffee
2016-01-08 10:09:45.328 attachRecordedDir: dir=file app=file
D:\node-rtsp-rtmp-server-master\server.coffee:46
    throw err;
    ^

Error: listen EACCES /tmp/node_rtsp_rtmp_videoControl
  at Object.exports._errnoException (util.js:870:11)
  at exports._exceptionWithHostPort (util.js:893:20)
  at Server._listen2 (net.js:1225:19)
  at listen (net.js:1274:10)
  at Server.listen (net.js:1364:5)
  at CustomReceiver.startUnix (D:\node-rtsp-rtmp-server-master\custom_receiver.coffee:91:27)
  at CustomReceiver.start (D:\node-rtsp-rtmp-server-master\custom_receiver.coffee:82:8)
  at StreamServer.start (D:\node-rtsp-rtmp-server-master\stream_server.coffee:216:21)
  at Object.<anonymous> (D:\node-rtsp-rtmp-server-master\server.coffee:34:14)
  at Object.<anonymous> (D:\node-rtsp-rtmp-server-master\server.coffee:1:1)
  at Module._compile (module.js:435:26)
  at Object.exports.run (D:\Program Files\nodejs\node_modules\coffee-script\lib\coffee-script\coffee-script.js:134:23)
  at compileScript (D:\Program Files\nodejs\node_modules\coffee-script\lib\coffee-script\command.js:224:29)
  at compilePath (D:\Program Files\nodejs\node_modules\coffee-script\lib\coffee-script\command.js:174:14)
  at Object.exports.run (D:\Program Files\nodejs\node_modules\coffee-script\lib\coffee-script\command.js:98:20)
  at Object.<anonymous> (D:\Program Files\nodejs\node_modules\coffee-script\bin\coffee:7:41)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:136:18)
  at node.js:963:3

**Comment by iizukanao** [comment]
I haven't tested against Windows, but please open config.coffee with a text editor and change the value of `receiverType` to `tcp`, and see if it works.

    receiverType: 'tcp'

**Comment by sunilkushwaha0101** [comment]
Thanks @iizukanao , Actually I was getting the same error in window.. but after changing the value of receiverType to tcp it's work :)
