### ISSUE TITLE
Unknown AMF0 data type: 17

### ISSUE THREAD

**Issue by gvsro** [iizukanao/node-rtsp-rtmp-server#36]
Trying to stream from Action Script 3:

Error: Unknown AMF0 data type: 17
  at parseAMF0Data (E:\cht\node-rtsp-rtmp-server-master\rtmp.coffee:264:15)
  at parseAMF0DataMessage (E:\cht\node-rtsp-rtmp-server-master\rtmp.coffee:202:14)
  at E:\cht\node-rtsp-rtmp-server-master\rtmp.coffee:2516:29
  at Sequent.<anonymous> (E:\cht\node-rtsp-rtmp-server-master\rtmp.coffee:2433:11)
  at Sequent.done (E:\cht\node-rtsp-rtmp-server-master\node_modules\sequent\lib\sequent.js:151:34)
  at E:\cht\node-rtsp-rtmp-server-master\rtmp.coffee:2546:21
  at RTMPSession.respondPublish (E:\cht\node-rtsp-rtmp-server-master\rtmp.coffee:1462:5)
  at RTMPSession.handleAMFCommandMessage (E:\cht\node-rtsp-rtmp-server-master\rtmp.coffee:2325:10)
  at E:\cht\node-rtsp-rtmp-server-master\rtmp.coffee:2541:16
  at RTMPSession.handleData (E:\cht\node-rtsp-rtmp-server-master\rtmp.coffee:2580:7)
  at Socket.<anonymous> (E:\cht\node-rtsp-rtmp-server-master\rtmp.coffee:2615:23)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:529:20)

Code used: [Link to PasteBin](http://pastebin.com/yVNrC9Pm)

**Comment by iizukanao** [comment]
@gvsro Thanks for reporting the issue!
Could you build a swf out of your AS3 code? I'm not familiar with Flash IDE...

**Comment by iizukanao** [comment]
@gvsro I've fixed some bugs in AMF0 parser. Could you please try again?

**Comment by gvsro** [comment]
@iizukanao i moved to nginx long ago, but i'll search the old files and report back.
