### ISSUE TITLE
Error: Unknown AMF0 data type: 108 when rtmp client stream

### ISSUE THREAD

**Issue by nvcken** [iizukanao/node-rtsp-rtmp-server#39]
2016-03-15 23:57:33.649 [rtmp] server started on port 1935
2016-03-15 23:57:33.650 [rtsp/http/rtmpt] server started on port 3000

2016-03-15 23:57:45.300 [rtmp:client=sjXr0K4l] connected
[rtmp: 1 sessions]
 sjXr0K4l: addr=192.168.1.103 port=50516
2016-03-15 23:57:45.321 [rtmp:handshake] warning: unknown message format, assuming format 1
2016-03-15 23:57:45.368 [rtmp:receive] unknown (not implemented) AMF data: FCPublish
2016-03-15 23:57:45.368 [rtmp:receive] unknown (not implemented) AMF data: releaseStream
2016-03-15 23:57:45.378 [rtmp] publish: stream=live/myStream publishingType=live
/Users/nvcken/think/node-rtsp-rtmp-server/server.js:47
    throw err;
    ^

Error: Unknown AMF0 data type: 108
    at parseAMF0Data (/Users/nvcken/think/node-rtsp-rtmp-server/rtmp.js:356:13)
    at parseAMF0StrictArray (/Users/nvcken/think/node-rtsp-rtmp-server/rtmp.js:212:16)
    at parseAMF0Data (/Users/nvcken/think/node-rtsp-rtmp-server/rtmp.js:341:16)
    at parseAMF0ECMAArray (/Users/nvcken/think/node-rtsp-rtmp-server/rtmp.js:231:16)
    at parseAMF0Data (/Users/nvcken/think/node-rtsp-rtmp-server/rtmp.js:310:16)
    at parseAMF0StrictArray (/Users/nvcken/think/node-rtsp-rtmp-server/rtmp.js:212:16)
    at parseAMF0Data (/Users/nvcken/think/node-rtsp-rtmp-server/rtmp.js:341:16)
    at parseAMF0ECMAArray (/Users/nvcken/think/node-rtsp-rtmp-server/rtmp.js:231:16)
    at parseAMF0Data (/Users/nvcken/think/node-rtsp-rtmp-server/rtmp.js:310:16)
    at parseAMF0DataMessage (/Users/nvcken/think/node-rtsp-rtmp-server/rtmp.js:249:16)

**Comment by iizukanao** [comment]
Thanks. Could you provide an swf or html that causes this error? Some users have reported the same kind of error, but I have been failed to reproduce the error.

**Comment by nvcken** [comment]
I don't use sf or html, I implement iOS feed camera streaming via RTMP to node server.
This is what I use for iOS https://github.com/jgh-/VideoCore to do rtmp feed

**Comment by nvcken** [comment]
I tried use pure js instead of coffee, then I got this error
```
/Users/nvcken/think/node-rtsp-rtmp-server/server.js:47
    throw err;
    ^

Error: Supplied key is too small
    at Error (native)
    at DiffieHellmanGroup.dhComputeSecret [as computeSecret] (crypto.js:414:26)
    at /Users/nvcken/think/node-rtsp-rtmp-server/rtmp.js:1229:41
    at /Users/nvcken/think/node-rtsp-rtmp-server/rtmp_handshake.js:160:16
    at InternalFieldObject.ondone (/Users/nvcken/think/node-rtsp-rtmp-server/rtmp_handshake.js:139:14)
```

**Comment by nvcken** [comment]
I rebuild and run twice again `Error: Unknown AMF0 data type: 108` always occurs

**Comment by iizukanao** [comment]
Thanks! I've reproduced the error and now I'm investigating the problem.

**Comment by nvcken** [comment]
素晴らしい

**Comment by iizukanao** [comment]
:smile: I've fixed AMF0 parser and it should work with VideoCore library. However, VideoCore has a bug too, and it sends invalid AMF0 data (created a [pull request](https://github.com/jgh-/VideoCore/pull/287)). So, the server still prints error message, but the streaming will work. Please give it a try.

**Comment by nvcken** [comment]
Now `Error: Unknown AMF0 data type: 108` is gone, but many times get `Error: Supplied key is too small` error then server crash.
I need to start server again, then restart iOS app too, then streaming works again.

**Comment by iizukanao** [comment]
OK, I've just fixed that problem too. Please pull the latest code from master.

**Comment by nvcken** [comment]
Wow, tried it. Cool.
I am curiously how did you reproduced with VideoCore and then found out where problem so fast.
Did you reproduce by the way integrate VideoCore to a blank Xcode project (add some code capture camera) then build to device ?

**Comment by iizukanao** [comment]
Thanks :smiley:
I just used a sample project included in VideoCore (SampleBroadcaster-Swift) and ran it on iOS device. Your assistance greatly helped, too!

**Comment by nvcken** [comment]
:+1:
