### ISSUE TITLE
Troubles starting the server

### ISSUE THREAD

**Issue by sifonsecac** [iizukanao/node-rtsp-rtmp-server#46]
I have downloaded the repository but i cant run the server. I'm on MacOs.

```
sudo coffee server.coffee
2016-05-24 10:34:51.098 attachRecordedDir: dir=file app=file
/Users/Sergio/Sites/node-rtsp-rtmp-server/server.coffee:46
    throw err;
    ^

Error: listen EADDRINUSE 0.0.0.0:1935
  at Object.exports._errnoException (util.js:837:11)
  at exports._exceptionWithHostPort (util.js:860:20)
  at Server._listen2 (net.js:1231:14)
  at listen (net.js:1267:10)
  at net.js:1376:9
  at doNTCallback3 (node.js:440:9)
  at process._tickCallback (node.js:346:17)
  at Function.Module.runMain (module.js:473:11)
  at startup (node.js:117:18)
  at node.js:951:3
```

**Comment by iizukanao** [comment]
@sifonsecac Maybe you have something running on port 1935? Stop that process and try again.

**Comment by sifonsecac** [comment]
Love you, you have just save my life! ❤️
