### ISSUE TITLE
Error right after opening stream with VLC

### ISSUE THREAD

**Issue by wildeyes** [iizukanao/node-rtsp-rtmp-server#49]
Windows 7.

```
$ node server.js
2016-06-14 11:20:17.366 attachRecordedDir: dir=file app=file
2016-06-14 11:20:17.379 [rtmp] server started on port 8080
2016-06-14 11:20:17.380 [rtsp/http/rtmpt] server started on port 3000
2016-06-14 11:20:24.099 [rtsp/http/rtmpt:client=c1] connected
2016-06-14 11:20:24.111 [rtsp/http/rtmpt:client=c2] connected
2016-06-14 11:20:26.386 [http] Requested file not found: C:\Users\User\node-rtsp-rtmp-server/public/favicon.ico
2016-06-14 11:20:42.702 [rtsp/http/rtmpt:client=c2] disconnected
[rtsp/http: 1 clients]
 c1: session=77152424 addr=127.0.0.1 port=2104
2016-06-14 11:21:11.832 [rtsp/http/rtmpt:client=c3] connected
2016-06-14 11:21:11.971 [mp4] warning: skipping unknown (not implemented) box type: tref (0x74726566)
2016-06-14 11:21:11.975 [mp4] warning: skipping unknown (not implemented) box type: hmhd (0x686d6864)
2016-06-14 11:21:11.977 [mp4] warning: skipping unknown (not implemented) box type: name (0x6e616d65)
2016-06-14 11:21:11.978 [mp4] warning: skipping unknown (not implemented) box type: hnti (0x686e7469)
2016-06-14 11:21:11.979 [mp4] warning: skipping unknown (not implemented) box type: hinf (0x68696e66)
2016-06-14 11:21:11.981 [mp4] warning: skipping unknown (not implemented) box type: tref (0x74726566)
2016-06-14 11:21:11.987 [mp4] warning: skipping unknown (not implemented) box type: hmhd (0x686d6864)
2016-06-14 11:21:11.988 [mp4] warning: skipping unknown (not implemented) box type: name (0x6e616d65)
2016-06-14 11:21:11.989 [mp4] warning: skipping unknown (not implemented) box type: hnti (0x686e7469)
2016-06-14 11:21:11.996 [mp4] warning: skipping unknown (not implemented) box type: hinf (0x68696e66)
2016-06-14 11:21:11.998 [mp4] warning: skipping unknown (not implemented) box type: hnti (0x686e7469)
C:\Users\User\node-rtsp-rtmp-server\server.js:47
    throw err;
    ^

TypeError: Cannot read property 'sequenceParameterSets' of null
    at MP4File.getSPS (C:\Users\User\node-rtsp-rtmp-server\mp4.js:174:21)
    at Function.MP4Stream.create (C:\Users\User\node-rtsp-rtmp-server\avstreams.js:310:37)
    at Object.api.get (C:\Users\User\node-rtsp-rtmp-server\avstreams.js:488:32)
    at C:\Users\User\node-rtsp-rtmp-server\rtsp.js:1502:32
    at RTSPServer.livePathConsumer (C:\Users\User\node-rtsp-rtmp-server\server.js:26:14)
    at RTSPServer.consumePathname (C:\Users\User\node-rtsp-rtmp-server\rtsp.js:1299:21)
    at RTSPServer.respondDescribe (C:\Users\User\node-rtsp-rtmp-server\rtsp.js:1490:19)
    at RTSPServer.respond (C:\Users\User\node-rtsp-rtmp-server\rtsp.js:2047:21)
    at RTSPServer.handleOnData (C:\Users\User\node-rtsp-rtmp-server\rtsp.js:1051:19)
    at Socket.<anonymous> (C:\Users\User\node-rtsp-rtmp-server\rtsp.js:512:28)
```

Also, using Big_buck_bunny.mp4 from http://camendesign.com/code/video_for_everybody/test.html.

**Comment by wildeyes** [comment]
This one http://techslides.com/demos/sample-videos/small.mp4 gave out 
```
2016-06-14 11:26:40.575 attachRecordedDir: dir=file app=file
2016-06-14 11:26:40.598 [rtmp] server started on port 8080
2016-06-14 11:26:40.601 [rtsp/http/rtmpt] server started on port 3000
2016-06-14 11:26:47.451 [rtsp/http/rtmpt:client=c1] connected
C:\Users\user\Documents\node-rtsp-rtmp-server\server.js:47
    throw err;
    ^

Error: read_byte error: no more data
    at Bits.read_byte (C:\Users\user\Documents\node-rtsp-rtmp-server\bits.js:255:17)
    at Bits.read_uint32 (C:\Users\user\Documents\node-rtsp-rtmp-server\bits.js:180:85)
    at MPEG4BitRateBox.read (C:\Users\user\Documents\node-rtsp-rtmp-server\mp4.js:2649:37)
    at MPEG4BitRateBox.Box (C:\Users\user\Documents\node-rtsp-rtmp-server\mp4.js:834:14)
    at new MPEG4BitRateBox (C:\Users\user\Documents\node-rtsp-rtmp-server\mp4.js:2641:52)
    at Function.Box.parse (C:\Users\user\Documents\node-rtsp-rtmp-server\mp4.js:1038:20)
    at AVCSampleEntry.read (C:\Users\user\Documents\node-rtsp-rtmp-server\mp4.js:2626:32)
    at AVCSampleEntry.Box (C:\Users\user\Documents\node-rtsp-rtmp-server\mp4.js:834:14)
    at AVCSampleEntry.VisualSampleEntry [as constructor] (C:\Users\user\Documents\node-rtsp-rtmp-server\mp4.js:1766:54)
    at new AVCSampleEntry (C:\Users\user\Documents\node-rtsp-rtmp-server\mp4.js:2616:51)
```

**Comment by wildeyes** [comment]
I am using this network stream in VLC: `rtsp://localhost:3000/file/test.mp4` for all of the tests.
I got it to work with a video from http://www.sample-videos.com/, the number 10 one.

It doesn't work though with ffmpeg streaming to the server, but I'll post that in another issue.

**Comment by alexandergorskih** [comment]
@wildeyes since http://www.sample-videos.com/ is down for a while, may I kindly ask you to provide sample that worked?

**Comment by wildeyes** [comment]
Cant find a similar issue, I'm closing and if it  happens again ill come back :)

**Comment by jazzy348** [comment]
I've found it! It seems to happen when the file is converted using FFMPEG to H264. You can download one at http://178.32.66.230/test.mp4
