### ISSUE TITLE
Socket error (c6): Error: write EPIPE

### ISSUE THREAD

**Issue by bmrinal** [iizukanao/node-rtsp-rtmp-server#51]
Getting this weird error whenever a client tries to connect via http. 
This code is running on a ubuntu version having node 4.4.5 version. Here is the full output:

`root@ubuntu-512mb-nyc3-01:~/node-rtsp-rtmp-server# sudo nodejs server.js 
2016-06-15 12:54:43.254 attachRecordedDir: dir=file app=file
2016-06-15 12:54:43.299 [rtmp] server started on port 1935
2016-06-15 12:54:43.301 [rtsp/http/rtmpt] server started on port 8080
2016-06-15 12:54:49.620 [rtsp/http/rtmpt:client=c1] connected
2016-06-15 12:54:49.974 [rtsp/http/rtmpt:client=c2] connected
2016-06-15 12:54:50.539 Socket error (c1): Error: write EPIPE
2016-06-15 12:54:50.540 [rtsp/http/rtmpt:client=c1] disconnected
`

**Comment by iizukanao** [comment]
That error is not harmful as long as you are not seeing any side effects. Please ignore them for now.

**Comment by bmrinal** [comment]
Well there is actually a side effect. The server doesn't serve anything and just says disconnect in the console.

**Comment by iizukanao** [comment]
What client are you using? I'm not experiencing such error on Debian 8.5 with curl.

```
$ coffee server.coffee
2016-06-23 16:54:17.524 attachRecordedDir: dir=file app=file
2016-06-23 16:54:17.555 [rtmp] server started on port 1935
2016-06-23 16:54:17.556 [rtsp/http/rtmpt] server started on port 8081
2016-06-23 16:54:20.235 [rtsp/http/rtmpt:client=c1] connected
2016-06-23 16:54:20.256 [rtsp/http/rtmpt:client=c1] disconnected
[rtsp/http: 0 clients]
```

```
$ curl -i http://localhost:8081/
HTTP/1.1 200 OK
Date: Thu, 23 Jun 2016 07:54:20 UTC
Server: node-rtsp-rtmp-server
Connection: close
Content-Length: 129
Content-Type: text/html; charset=utf-8

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Hello World</title>
</head>
<body>
Hello, World!
</body>
</html>
```

In the above example, port 8081 is used instead of 80.

**Comment by bmrinal** [comment]
VLC

Regards,
Mrinal Purohit

**Comment by iizukanao** [comment]
What URL do you use in VLC?

**Comment by bmrinal** [comment]
I tried this in browser: http://104.236.24.31:8080/video.mp4
and in VLC, i tried rtsp://104.236.24.31:8080/video.mp4. I have a test machine running on a vps, can provide you access if you want to test.

**Comment by iizukanao** [comment]
OK, thanks.

Files in public/ directory will be served via http:// URL. For example, when you put public/video.mp4, it's accessible via http://HOST:8080/video.mp4

On the other hand, files in file/ directory will be served via rtsp:// and rtmp:// URLs. For example, when you put file/video.mp4, it's accessible via rtsp://HOST:8080/file/video.mp4 and rtmp://HOST/file/mp4:video.mp4

**Comment by bmrinal** [comment]
Let me give it a try. Thanks.
Quick question, in http method, is it that, the full file gets downloaded first and then gets played?

**Comment by bmrinal** [comment]
I moved the file in the file/ directory and tried rtsp://104.236.24.31:8080/file/video.mp4 and i get the following error in console:

`/root/node-rtsp-rtmp-server/server.js:47
    throw err;
    ^

ReferenceError: box is not defined
    at Function.Box.readHeader (/root/node-rtsp-rtmp-server/mp4.js:915:9)
    at Function.Box.parse (/root/node-rtsp-rtmp-server/mp4.js:936:12)
    at MP4File.parse (/root/node-rtsp-rtmp-server/mp4.js:107:19)
    at Function.MP4Stream.create (/root/node-rtsp-rtmp-server/avstreams.js:308:15)
    at Object.api.get (/root/node-rtsp-rtmp-server/avstreams.js:488:32)
    at /root/node-rtsp-rtmp-server/rtsp.js:1502:32
    at RTSPServer.livePathConsumer (/root/node-rtsp-rtmp-server/server.js:26:14)
    at RTSPServer.consumePathname (/root/node-rtsp-rtmp-server/rtsp.js:1299:21)
    at RTSPServer.respondDescribe (/root/node-rtsp-rtmp-server/rtsp.js:1490:19)
    at RTSPServer.respond (/root/node-rtsp-rtmp-server/rtsp.js:2047:21)
`

**Comment by iizukanao** [comment]
Sorry, I've just fixed that bug. Please pull the latest code and try again.

As for mp4 streaming in HTTP, it depends on client player and the format of mp4 file. To prepare an mp4 file for streaming, see the first item in [this answer](http://stackoverflow.com/a/10330501).

**Comment by bmrinal** [comment]
Thanks checking...

**Comment by bmrinal** [comment]
Yes, moving the faststart to start does make the video stream instantaneously. 
I have a question. When I am using this server for http streaming, is it same as sending the mp4 files directly to mobile clients over http or this does some magic before sending to html5 so that they gets played smoothly?

**Comment by iizukanao** [comment]
For HTTP, this server just sends mp4 content as-is in the same manner as Apache or nginx. Range header is also supported to allow seeking.

**Comment by bmrinal** [comment]
that helps! Thanks.
