### ISSUE TITLE
Connect to RTSP stream from VLC

### ISSUE THREAD

**Issue by mihaj** [iizukanao/node-rtsp-rtmp-server#64]
Hi guys.

I have installed node-rtsp-rtmp-server successfully and started it with start_server.sh. Here is the output:

```
2016-09-11 12:21:38.173 attachRecordedDir: dir=file app=file
2016-09-11 12:21:38.219 [rtmp] server started on port 1935
2016-09-11 12:21:38.221 [rtsp/http/rtmpt] server started on port 5887
```

Then I just try to connect to it with VLC and I get this:

```
/home/pi/node-rtsp-rtmp-server/server.coffee:46
    throw err;
          ^
TypeError: Cannot call method 'slice' of null
  at RTSPServer.livePathConsumer (/home/pi/node-rtsp-rtmp-server/server.coffee:13:38)
  at RTSPServer.consumePathname (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:1122:8)
  at RTSPServer.respondDescribe (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:1318:6)
  at RTSPServer.respond (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:1890:8)
  at RTSPServer.handleOnData (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:906:6)
  at Socket.<anonymous> (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:449:12)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:748:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:410:10)
  at emitReadable (_stream_readable.js:406:5)
  at readableAddChunk (_stream_readable.js:168:9)
  at Socket.Readable.push (_stream_readable.js:130:10)
  at TCP.onread (net.js:528:21)
```

Am I missing a package? Coffee Script is at version 1.10.0

Thank you for any help.

**Comment by iizukanao** [comment]
What URL did you enter in VLC? It should be something like rtsp://localhost:80/file/video.mp4

**Comment by mihaj** [comment]
Hi Iizukanao!

I just entered something like: rtsp://localhost:80

Should I add /file/video.mp4 for live stream? Where do I configure that?

**Comment by iizukanao** [comment]
Yes, URL must contain the filename of the video you want to watch. For example, when you put your_video.mp4 in node-rtsp-rtmp-server/file/ directory, open rtsp://localhost:80/file/your_video.mp4 in VLC.

**Comment by mihaj** [comment]
Hmm. I dont have any file. I am doing live stream with PiCam like this:

`./picam --alsadev hw:1,0 --rtspout -w 800 -h 480 -v 500000 -f 20`

**Comment by iizukanao** [comment]
When you use picam, open rtsp://RASPI_IP:80/live/picam, where RASPI_IP is your Raspberry Pi's IP address.

**Comment by cuimiao187561** [comment]
HI 
when I open " rtsp://192.16.123.67:80/file/test.mp4 "in VLC butI just try to connect to it with VLC and I get this:
     
     /home/pi/node-rtsp-rtmp-server/server.coffee:46
    throw err;
          ^
TypeError: Cannot call method 'slice' of null
  at RTSPServer.livePathConsumer (/home/pi/node-rtsp-rtmp-server/server.coffee:13:38)
  at RTSPServer.consumePathname (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:1122:8)
  at RTSPServer.respondDescribe (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:1318:6)
  at RTSPServer.respond (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:1890:8)
  at RTSPServer.handleOnData (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:906:6)
  at Socket.<anonymous> (/home/pi/node-rtsp-rtmp-server/rtsp.coffee:449:12)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:748:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:410:10)
  at emitReadable (_stream_readable.js:406:5)
  at readableAddChunk (_stream_readable.js:168:9)
  at Socket.Readable.push (_stream_readable.js:130:10)
  at TCP.onread (net.js:528:21)
Please how to slove

**Comment by iizukanao** [comment]
@cuimiao187561 In VLC, Click "File" menu -> "Open Network...", then enter **rtsp://192.16.123.67:80/file/test.mp4** into the URL field.

**Comment by iizukanao** [comment]
@cuimiao187561 Please create a new issue if you are still having problems.
