### ISSUE TITLE
RTSP Strem connect with vlc errored when played with rtsp://localhost:80/file/video.mp4

### ISSUE THREAD

**Issue by AmazingW** [iizukanao/node-rtsp-rtmp-server#66]
Also it already run in my mac successful, i followed the direction of the md file. But when i run rtsp://localhost:80/file/video.mp4

```
2016-11-07 15:43:18.961 [rtsp/http/rtmpt:client=c1] connected
/Users/qifeiwu/Desktop/rtsp_test/node-rtsp-rtmp-server/server.js:47
    throw err;
    ^

Error: bits.get_string: the string is not null-terminated
    at Bits.get_string (/Users/qifeiwu/Desktop/rtsp_test/node-rtsp-rtmp-server/bits.js:458:15)
    at HandlerBox.read (/Users/qifeiwu/Desktop/rtsp_test/node-rtsp-rtmp-server/mp4.js:1525:24)
    at HandlerBox.Box (/Users/qifeiwu/Desktop/rtsp_test/node-rtsp-rtmp-server/mp4.js:834:14)
    at new HandlerBox (/Users/qifeiwu/Desktop/rtsp_test/node-rtsp-rtmp-server/mp4.js:1512:47)
    at Function.Box.parse (/Users/qifeiwu/Desktop/rtsp_test/node-rtsp-rtmp-server/mp4.js:958:18)
    at MediaBox.Container.read (/Users/qifeiwu/Desktop/rtsp_test/node-rtsp-rtmp-server/mp4.js:1059:19)
    at MediaBox.Box (/Users/qifeiwu/Desktop/rtsp_test/node-rtsp-rtmp-server/mp4.js:834:14)
    at MediaBox.Container [as constructor] (/Users/qifeiwu/Desktop/rtsp_test/node-rtsp-rtmp-server/mp4.js:1051:46)
    at new MediaBox (/Users/qifeiwu/Desktop/rtsp_test/node-rtsp-rtmp-server/mp4.js:1127:45)
    at Function.Box.parse (/Users/qifeiwu/Desktop/rtsp_test/node-rtsp-rtmp-server/mp4.js:952:18)
```

and the video type is MPEG-4.

the vlc shows this error
![image](https://cloud.githubusercontent.com/assets/17867268/20050007/bbc11ca0-a501-11e6-8fe8-628af47148c8.png)

**Comment by iizukanao** [comment]
@AmazingW I think your mp4 file is broken. Try another mp4 file. Or upload the file in question to somewhere so that I can reproduce that problem.

**Comment by AmazingW** [comment]
I changed a file ,it worked well. Thx
