### ISSUE TITLE
TypeError: Parameter "url" must be a string, not boolean

### ISSUE THREAD

**Issue by ad34** [iizukanao/node-rtsp-rtmp-server#79]
I made a test using telestream wirecast as a client for rtmp server , seems to work fine but after stopping the stream I got a server crash with the following callstack :

TypeError: Parameter "url" must be a string, not boolean
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
    at RTMPSession.respondPublish (/home/node-rtsp-rtmp-server/rtmp.coffee:1492:21)
    at RTMPSession.handleAMFCommandMessage (/home/node-rtsp-rtmp-server/rtmp.coffee:2242:23)
    at /home/node-rtsp-rtmp-server/rtmp.coffee:2532:38
    at Sequent.<anonymous> (/home/node-rtsp-rtmp-server/rtmp.coffee:2353:22)
    at Sequent.done (/home/node-rtsp-rtmp-server/node_modules/sequent/lib/sequent.js:151:34)

**Comment by iizukanao** [comment]
@ad34 Thanks for reporting an issue! I've just fixed a few bugs. Could you pull the latest code and give it another try?

**Comment by ad34** [comment]
@iizukanao wow thanks, the issue is fixed. sometimes wirecast complains about an error (-4018) but it start to broadcast the stream anyway !

**Comment by iizukanao** [comment]
@ad34 Thank you for the feedback! I think error -4018 is caused by other problem with your network connection. However, if you are sure that it is a bug in node-rtsp-rtmp-server, please open another issue. Thanks!
