### ISSUE TITLE
RTMP Server does not work: "hdlr: pre_defined is not 0 (got 1835560050)"

### ISSUE THREAD

**Issue by Kiesco08** [iizukanao/node-rtsp-rtmp-server#87]
I'm having a hard time debugging it. Here is the stacktrace:

2017-05-21 13:18:45.072 [rtmp] server started on port 1935
2017-05-21 13:18:45.072 [rtsp/http/rtmpt] server started on port 80
2017-05-21 13:18:47.269 [rtmp:client=ty6MW6MD] connected
[rtmp: 1 sessions]
 ty6MW6MD: addr=192.168.2.11 port=59822
2017-05-21 13:18:47.409 [rtmp:receive] unknown (not implemented) AMF command: _checkbw
2017-05-21 13:18:47.422 [rtmp:receive] unknown (not implemented) AMF command: getStreamLength
2017-05-21 13:18:47.423 [rtmp:client=ty6MW6MD] requested stream file/mp4:video.mp4
2017-05-21 13:18:47.432 [mp4] warning: skipping unknown (not implemented) box type: wide (0x77696465)
/Users/OrbitHub/Dropbox/FreeFooty/Coding/node-rtsp-rtmp-server/server.js:47
    throw err;
    ^

Error: hdlr: pre_defined is not 0 (got 1835560050)
    at HandlerBox.read (/Users/OrbitHub/Dropbox/FreeFooty/Coding/node-rtsp-rtmp-server/mp4.js:1521:15)
    at HandlerBox.Box (/Users/OrbitHub/Dropbox/FreeFooty/Coding/node-rtsp-rtmp-server/mp4.js:834:14)
    at new HandlerBox (/Users/OrbitHub/Dropbox/FreeFooty/Coding/node-rtsp-rtmp-server/mp4.js:1512:47)
    at Function.Box.parse (/Users/OrbitHub/Dropbox/FreeFooty/Coding/node-rtsp-rtmp-server/mp4.js:958:18)
    at MediaBox.Container.read (/Users/OrbitHub/Dropbox/FreeFooty/Coding/node-rtsp-rtmp-server/mp4.js:1059:19)
    at MediaBox.Box (/Users/OrbitHub/Dropbox/FreeFooty/Coding/node-rtsp-rtmp-server/mp4.js:834:14)
    at MediaBox.Container [as constructor] (/Users/OrbitHub/Dropbox/FreeFooty/Coding/node-rtsp-rtmp-server/mp4.js:1051:46)
    at new MediaBox (/Users/OrbitHub/Dropbox/FreeFooty/Coding/node-rtsp-rtmp-server/mp4.js:1127:45)
    at Function.Box.parse (/Users/OrbitHub/Dropbox/FreeFooty/Coding/node-rtsp-rtmp-server/mp4.js:952:18)
    at TrackBox.Container.read (/Users/OrbitHub/Dropbox/FreeFooty/Coding/node-rtsp-rtmp-server/mp4.js:1059:19)

**Comment by bhargavghodasara** [comment]
same issue facing
did you find any solution?

**Comment by iizukanao** [comment]
Sorry, I can't reproduce that error. Can anyone provide a sample MP4 file to me? Then, I can fix it.
