### ISSUE TITLE
Unknown SDP audio channel.

### ISSUE THREAD

**Issue by pedroSG94** [iizukanao/node-rtsp-rtmp-server#91]
Hi, 
I'm testing my library RTSP UDP with your server and I get this error in the connection:
```
2017-07-07 19:06:58.192 [rtsp/http/rtmpt:client=c1] connected
2017-07-07 19:06:58.214 Unknown (not implemented) SDP: i=N/A
2017-07-07 19:06:58.214 Unknown (not implemented) SDP: thread=0 0
2017-07-07 19:06:58.221 Error: rtpmap attribute in SDP must have audio channels; assuming 2
```
My library is working with wowza but no with this server. I assume that this server need different connection request to work and that is the error but your server return me a 200 response. 
Could you tell me the error reason?
My library is this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java
It work with H264 and ACC.

In RTSP TCP i got this error:

```
2017-07-07 19:23:36.561 [rtsp/http/rtmpt:client=c1] connected
2017-07-07 19:23:36.567 Unknown (not implemented) SDP: i=N/A
2017-07-07 19:23:36.567 Unknown (not implemented) SDP: thread=0 0
2017-07-07 19:23:36.567 Error: rtpmap attribute in SDP must have audio channels; assuming 2
/home/pedro/AndroidStudioProjects/node-rtsp-rtmp-server/server.coffee:46
    throw err;
    ^

TypeError: Cannot read property 'videoData' of undefined
  at RTSPServer.onInterleavedRTPPacketFromClient (/home/pedro/AndroidStudioProjects/node-rtsp-rtmp-server/rtsp.coffee:803:58)
  at RTSPServer.handleOnData (/home/pedro/AndroidStudioProjects/node-rtsp-rtmp-server/rtsp.coffee:842:8)
  at Socket.<anonymous> (/home/pedro/AndroidStudioProjects/node-rtsp-rtmp-server/rtsp.coffee:452:12)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
```

**Comment by GsandeepR** [comment]
I am facing the same issue ,did you find any fix?

**Comment by pedroSG94** [comment]
Yes. the error was that I had an error in ANNOUNCE packet. 
I wrote:
```
RTP/AVP96
```
(Where 96 is my payload)
Instance of:
```
RTP/AVP 96
```
